

export const CountryErrors = {
    COUNTRY_NOT_FOUND: 'Country not found',
    COUNTRY_ALREADY_EXISTS: 'Country already exists',
    COUNTRY_NAME_ALREADY_EXISTS: 'Country name already exists',
    COUNTRY_CODE_ALREADY_EXISTS: 'Country code already exists',
    COUNTRY_CODE_NOT_FOUND: 'Country code not found',
    COUNTRY_NAME_NOT_FOUND: 'Country name not found',
    COUNTRY_CODE_INVALID: 'Country code invalid',
    COUNTRY_NAME_INVALID: 'Country name invalid',
    COUNTRY_CODE_REQUIRED: 'Country code required',
    COUNTRY_NAME_REQUIRED: 'Country name required',
}

export const CountryErrorCode = {
    COUNTRY_NOT_FOUND: 'COUNTRY_NOT_FOUND',
    COUNTRY_ALREADY_EXISTS: 'COUNTRY_ALREADY_EXISTS',
    COUNTRY_NAME_ALREADY_EXISTS: 'COUNTRY_NAME_ALREADY_EXISTS',
    COUNTRY_CODE_ALREADY_EXISTS: 'COUNTRY_CODE_ALREADY_EXISTS',
    COUNTRY_CODE_NOT_FOUND: 'COUNTRY_CODE_NOT_FOUND',
    COUNTRY_NAME_NOT_FOUND: 'COUNTRY_NAME_NOT_FOUND',
    COUNTRY_CODE_INVALID: 'COUNTRY_CODE_INVALID',
    COUNTRY_NAME_INVALID: 'COUNTRY_NAME_INVALID',
    COUNTRY_CODE_REQUIRED: 'COUNTRY_CODE_REQUIRED',
    COUNTRY_NAME_REQUIRED: 'COUNTRY_NAME_REQUIRED',
}
